version: '3.8'

services:
  redis:
    image: redis:6
    container_name: recruitment-manager-api-redis
    environment:
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "6390:6379"

  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    container_name: recruitment-manager-api-db
    environment:
      MYSQL_ROOT_PASSWORD: recruitment_manager
      MYSQL_USER: recruitment_manager
      MYSQL_PASSWORD: recruitment_manager
      TZ: 'Asia/Ho_Chi_Minh'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./docker/db/mysql-data:/var/lib/mysql
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3308:3306
    user: mysql

  php:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: recruitment-manager-php
    links:
      - mysql:mysql
      - redis:redis
    ports:
      - "9000:9000"
    volumes:
      - .:/application
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  webserver:
    image: nginx:1.17.10
    container_name: recruitment-manager-api-webserver
    working_dir: /application
    links:
      - php:fpm
    environment:
      - FPM_HOST=fpm
      - FPM_PORT=9000
    volumes:
      - .:/application
      - ./:/var/www/html
      - ./storage/logs/nginx/:/var/log/nginx
      - ./docker/nginx_conf:/etc/nginx/conf.d/
    ports:
      - "8010:80"

  s3:
    image: minio/minio
    container_name: recruitment-manager-api-s3
    ports:
      - 9010:9010
      - 9020:9020
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./docker/minio:/data
    command: server /data --address :9010 --console-address :9020
